### ISSUE TITLE
Run instructions

### ISSUE THREAD

**Issue by akshat-khare** [Cubusky/com.cubusky.heatgrids#6]
Amazing work! I wish to run this in my unity application. Can you please provide a video tutorial or detailed setup instructions please?

**Comment by CaseyHofland** [comment]
Hi sorry for seeing this so late!

You're in luck, I'm very busy on getting this ready for `1.0.0`, and I'll provide a lot better documentation for it (you'll note it is currently in `0.2.0-exp`).

I can't give you a clear timeline. I _want_ to say 2 weeks, but expect a month from now just to be safe. And most importantly: I'm soloing this, so nothing here is a hard promise.

When would you say you need this?

**Comment by CaseyHofland** [comment]
Bonus: I'm writing something that lets you save/load to/from AWS if that's something you're interested in. AWS integration will be in another package when it's ready.

**Comment by akshat-khare** [comment]
Hi @CaseyHofland Thanks for the response. 
I need this for a custom heatmap implementation in Unity and would love to use your optimizations. Is there anyway I can help to expedite this. AWS integration would be totally awesome. Totally can help with that too. Need this super urgent at this moment so happy to collaborate on this. Thank you for open sourcing this.

**Comment by CaseyHofland** [comment]
I see. Not really, because it's basically already finished, the reason I haven't updated my github yet is because I have been building this in tandem with [Ghosts](https://github.com/Cubusky/com.cubusky.ghosts) (there's no actual code on that repo yet). I wanted to write documentation only when I have both of them finished.

I can totally bump this version up to `0.9.0-pre` though. It will have everything that `1.0.0` will have except documentation. I'll have `0.9.0-pre` out by Friday then (probably today but no promises, I don't know what issues I'll run into).



Once it's out, it is super-easy to start using heatgrids.

To Record:
1. Add a `Heatgrid Recorder` to your player.
2. Choose how you want to save it (AWS integration is still in development, for now you can use the `DirectorySaverLoader` for testing).

To Visualize:
1. Add a `ParticleSystemVisualizer` to an object (probably something top-level that you can remove from builds).
2. [Read this](https://cubusky.github.io/com.cubusky.heatgrids/manual/Visualization.html#particle-solution)

**Comment by CaseyHofland** [comment]
Hey thought I'd give a bit of an update on my progress:

I made all the changes I needed to do in `com.cubusky.core` in order for me to settle on a heatgrid implementation. Now all I need to do for `0.9.0-pre` is:
1. Remove old code and streamline implementation.
2. Push a new pre-release version of `com.cubusky.core`
3. Push a new pre-release version of `com.cubusky.heatgrids`

I'll omit XML code comments for now and push them in `0.9.0-pre.1`. Friday seemed initially a good guess, there was some streamlining I wanted to do first (look out for `ISaver`, it's meaty).

**Comment by CaseyHofland** [comment]
@akshat-khare should be finished today. Check the develop branch of this package and [com.cubusky.core](https://github.com/Cubusky/com.cubusky.core/tree/develop), I'm not sitting still.

**Comment by CaseyHofland** [comment]
@akshat-khare It is finished, under `0.3.0-exp`. Since `com.cubusky.core` is such an integral part of the `Cubusky` family I did in the end decide to do all the documentation for it before pushing this version. The good news is of course that you can use `com.cubusky.core` for a lot of things as well, and now it's all properly documented.

The final implementation for you I'd suggest:

To Record:
1. Add a `HeatgridRecorder` to your player.
2. Choose how you want to save it (AWS integration is still in development, for now you can use the DirectorySaverLoader for testing).

To Visualize:
1. Add a `HeatgridLoader` to an empty object (it is deprecated but when the next version comes out, conversion will be minimal).
2. Add a `ParticleSystemVisualizer` on the same object.
3. Reference the `HeatgridLoader` in `ParticleSystemVisualizer.heatgrid`.
4. Use the context menu to visualize the `Heatgrid`.
  a. Open the context menu by right-clicking the `ParticleSystemVisualizer`.
  b. SetAverageSteps will set the min- and max steps to a reasonable range.
  c. SetMaxParticles will set the maximum particles needed to visualize the heatgrid.
  d. Visualize will visualize the heatgrid.

As to your suggestions for contributing to the package, you are always very welcome to! Right now I would wait until version `1.0.0`, but afterwards it should be very easy to add your own `IHeatgridVisualizer`, `ISaverLoader`, or `IHeatgrid` implementation, it is all very modular!

I'm closing this issue now but feel free to reach out to me on the [Unity forums](https://forum.unity.com/members/caseyhofland.1082046/).
